name: CI/CD MLflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CSV_URL: "MLProject/train_pca.csv"
  TARGET_VAR: "Credit_Score"
  IMAGE_NAME: cc

jobs:
  advanced:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python 3.12.7
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # 3️⃣ Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install mlflow
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # 4️⃣ Set MLflow Tracking URI
      - run: |
          echo "MLFLOW_TRACKING_URI=./mlruns" >> $GITHUB_ENV

      # 5️⃣ Run MLflow Project (retrain model)
      - run: |
          mlflow run MLProject --env-manager=local

      # 6️⃣ Get latest run_id dari folder mlruns
      - run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7️⃣ Upload artefak ke Google Drive
      - env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python scripts/upload_to_gdrive.py

      # 8️⃣ Login ke Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 9️⃣ Build Docker Image
      - run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "$IMAGE_NAME"

      # 🔟 Tag Docker Image
      - run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest

      # 1️⃣1️⃣ Push Docker Image ke Docker Hub
      - run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest
