name: Basic CI - MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check environment variable (contoh)
      - name: Check Env
        run: echo "CSV_PATH=$CSV_PATH"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn numpy cloudpickle

      # 5. Run MLflow Project
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local

      # 6. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "Latest MLflow RUN_ID: $RUN_ID"
